pretrained_base_model_path: "./pretrained_weights/sd-image-variations-diffusers"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"


denoising_unet_path: './pretrained_weights/denoising_unet_acc.pth'
reference_unet_path: "./pretrained_weights/reference_unet.pth"
pose_encoder_path: "./pretrained_weights/pose_encoder.pth"
motion_module_path: './pretrained_weights/motion_module_acc.pth'

audio_mapper_path: "./pretrained_weights/audio_mapper-50000.pth"
wav2vec2_audio_guider_path: "./pretrained_weights/wav2vec2-base-960h"
auto_flow_path: "./pretrained_weights/AutoFlow"
audio_model_path: "./pretrained_weights/audio_processor/tiny.pt"
inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

# --- PIPELINE SETTINGS ---
# We use a single fixed entry so your Python script doesn't have to keep changing the YAML
test_cases:
  "./assets/therapist_ref.png":
    - "../audio_video/therapist_response.wav"   # Audio from ChatTTS
    - "./assets/halfbody_demo/pose/01/"         # Default pose folder

# --- 8GB VRAM OPTIMIZATIONS ---
# These must be explicitly set to avoid OOM (Out of Memory)
width: 512
height: 512
fps: 30
iteration: 1
seed: 42
cfg_scale: 2.5
sample_steps: 6      # Critical for ACC version
context_frames: 12   # Matches the new clip-frames
context_overlap: 4